#!/usr/bin/env bash
# ============================================================================
# 05-configure-tailscale.sh  —  homelab-siem
#
# Installs Tailscale, joins your tailnet, and exposes Grafana over the
# tailscale0 interface (in addition to 127.0.0.1) by generating a gitignored
# docker-compose.override.yml with the Pi's tailscale IP, then re-deploying.
#
# Why an override file: the tailscale IP doesn't exist until Tailscale is up,
# which is AFTER 04-deploy-stack.sh ran. The base compose binds Grafana to
# loopback only; this script adds the tailnet binding once we know the IP.
#
# Telegram alerting is Phase 5 work too, but it's configured inside Grafana
# (a contact point), not here. See docs/ (added in a later phase).
#
# Auth: set TS_AUTHKEY in your environment for unattended join, otherwise
# `tailscale up` prints a URL to authenticate in your browser.
# Run as pi2 (uses sudo).
# ============================================================================
set -euo pipefail

c_blue=$'\033[1;34m'; c_yellow=$'\033[1;33m'; c_red=$'\033[1;31m'; c_green=$'\033[1;32m'; c_off=$'\033[0m'
info() { printf '%s[*]%s %s\n' "$c_blue"   "$c_off" "$*"; }
ok()   { printf '%s[+]%s %s\n' "$c_green"  "$c_off" "$*"; }
warn() { printf '%s[!]%s %s\n' "$c_yellow" "$c_off" "$*" >&2; }
die()  { printf '%s[x]%s %s\n' "$c_red"    "$c_off" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] && die "Run as your normal user (pi2), not root."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_DIR/.env"
COMPOSE_FILE="$REPO_DIR/docker/docker-compose.yml"
OVERRIDE_FILE="$REPO_DIR/docker/docker-compose.override.yml"

[[ -f "$ENV_FILE" ]] || die "No .env at $ENV_FILE."
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# ---------------------------------------------------------------------------
# 1. Install Tailscale (skip if present)
# ---------------------------------------------------------------------------
if command -v tailscale >/dev/null 2>&1; then
  ok "Tailscale already installed ($(tailscale version | head -1))."
else
  info "Installing Tailscale (official script, ARM64)..."
  curl -fsSL https://tailscale.com/install.sh | sh
  ok "Tailscale installed."
fi
sudo systemctl enable --now tailscaled

# ---------------------------------------------------------------------------
# 2. Join the tailnet
# ---------------------------------------------------------------------------
if tailscale status >/dev/null 2>&1 && [[ -n "$(tailscale ip -4 2>/dev/null || true)" ]]; then
  ok "Already connected to a tailnet."
else
  if [[ -n "${TS_AUTHKEY:-}" ]]; then
    info "Joining tailnet with TS_AUTHKEY (unattended)..."
    sudo tailscale up --authkey "$TS_AUTHKEY" --hostname jmacpi2
  else
    warn "No TS_AUTHKEY set. 'tailscale up' will print a URL — open it in your"
    warn "browser and approve this device, then this script continues."
    sudo tailscale up --hostname jmacpi2
  fi
fi

# ---------------------------------------------------------------------------
# 3. Resolve the tailscale IPv4 address
# ---------------------------------------------------------------------------
TS_IP="$(tailscale ip -4 2>/dev/null | head -1)"
[[ -n "$TS_IP" ]] || die "Could not determine tailscale IPv4. Run 'tailscale status' to debug."
ok "This Pi's tailscale IP: $TS_IP"

# ---------------------------------------------------------------------------
# 4. Generate the gitignored override that binds Grafana to tailscale0
#    Compose merges 'ports' by appending, so the base 127.0.0.1 binding stays
#    and this ADDS the tailnet binding (no duplicate).
# ---------------------------------------------------------------------------
info "Writing $OVERRIDE_FILE (gitignored)..."
cat > "$OVERRIDE_FILE" <<EOF
# AUTO-GENERATED by 05-configure-tailscale.sh — do not commit (gitignored).
# Adds the tailscale0 binding for Grafana. Regenerate by re-running 05.
services:
  grafana:
    ports:
      - "${TS_IP}:3000:3000"
EOF
ok "Override written (Grafana will bind 127.0.0.1 + ${TS_IP})."

# ---------------------------------------------------------------------------
# 5. Re-deploy with base + override merged
# ---------------------------------------------------------------------------
if docker info >/dev/null 2>&1; then SUDO=""; else SUDO="sudo"; fi
info "Re-applying the stack with the tailscale binding..."
$SUDO docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" up -d
ok "Stack re-deployed."

# ---------------------------------------------------------------------------
# 6. Verify Grafana answers on the tailscale IP
# ---------------------------------------------------------------------------
sleep 3
if curl -fsS "http://${TS_IP}:3000/api/health" >/dev/null 2>&1; then
  ok "Grafana is reachable over Tailscale."
else
  warn "Grafana not answering on ${TS_IP}:3000 yet — give it a few seconds and retry:"
  warn "    curl http://${TS_IP}:3000/api/health"
fi

echo
ok "Remote access ready. From any device on your tailnet:"
info "    Grafana:  http://${TS_IP}:3000   (or http://jmacpi2:3000 with MagicDNS)"
info "    SSH:      ssh pi2@${TS_IP}"
echo
warn "NOTE: every future deploy must include BOTH compose files, e.g.:"
warn "    docker compose -f docker-compose.yml -f docker-compose.override.yml up -d"
warn "    (Compose auto-loads the override only when you DON'T pass -f. 04 uses -f,"
warn "     so use the form above, or just re-run this script.)"
ok "Next: ./install/06-harden.sh"
